services:
  web:
    build: .
    ports:
      - "3000:80"
    env_file:
      - path: .env
        required: true
    environment:
      - NODE_ENV=production
        APP_NAME=${APP_NAME}
        KEY_SECRET=${KEY_SECRET}
        SHARED_SECRET=${SHARED_SECRET}
        VITE_API_URL_DEV=${VITE_API_URL_DEV}
        VITE_API_URL_PRODUCTION=${VITE_API_URL_PRODUCTION}
